id: A88BB05E7
title: Light Offering Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:12:17.589357
  last_modified_at: 2022-03-01 04:12:17.589360
