id: A88BB05E7
title: 'The Torch of Wisdom: A Method of Offering Butter Lamps Based on Ārya Mañjuśrī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:12:17.597576
  last_modified_at: 2022-03-01 04:12:17.597578
