id: A88BB05E7
title: Aspiration for Electric Lamps
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:12:17.583699
  last_modified_at: 2022-03-01 04:12:17.583706
