id: A88BB05E7
title: 'Ocean of Offering Clouds: A Light Offering Prayer'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:12:17.595958
  last_modified_at: 2022-03-01 04:12:17.595962
