id: A88BB05E7
title: Lamp Aspiration Prayer (from the Tsok Offering 'A Rain of Blessings')
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:12:17.586446
  last_modified_at: 2022-03-01 04:12:17.586449
